### ISSUE TITLE
Error while compiling eq3_v2/climate.py

### ISSUE THREAD

**Issue by ariznaf** [ayufan/esphome-components#29]
I am trying to use this eq3_v2 component in esphome.

I have included the advised include lines:
```
external_components:
  - source: github://ayufan/esphome-components
.......

# time is required by `eq3_v2` to send
# an accurate time spec when requesting
# current state
time:
  - platform: sntp
    id: sntp_time

# refresh component state every 30mins,
# and announce it to Home Assistant MQTT
climate:
  - platform: eq3_v2
    id: office_eq3
    name: Office EQ3
    mac_address: 00:1A:22:12:5B:34
    update_interval: 30min
    valve: # optional, allows to see valve state in %
      name: Office EQ3 Valve State
      expire_after: 61min

# allow to force refresh component state
switch:
  - platform: template
    name: "Refresh Office EQ3"
    lambda: "return false;"
    turn_on_action:
      - component.update: office_eq3
```

But then I get an error saying that the eq3_v2.climate component cannot be found
```
INFO Reading configuration /config/esphome/conrad-salajuegos.yaml...
ERROR Unable to load component eq3_v2.climate:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/d599fc18/components/eq3_v2/climate.py", line 23, in <module>
    cv.Optional(CONF_VALVE): sensor.sensor_schema(UNIT_PERCENT, ICON_PERCENT, 0),
TypeError: sensor_schema() takes from 0 to 1 positional arguments but 3 were given
INFO Detected timezone 'Europe/Madrid'
Failed config
```

Assuming it was a documentation error, I have changed the include lines to:
```
external_components:
  - source: github://ayufan/esphome-components/components

```

But now I get an error in the climate.py code:
```
INFO Reading configuration /config/esphome/conrad-salajuegos.yaml...
ERROR Unable to load component eq3_v2.climate:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/d599fc18/components/eq3_v2/climate.py", line 23, in <module>
    cv.Optional(CONF_VALVE): sensor.sensor_schema(UNIT_PERCENT, ICON_PERCENT, 0),
TypeError: sensor_schema() takes from 0 to 1 positional arguments but 3 were given
INFO Detected timezone 'Europe/Madrid'
Failed config
```

It seems that there is a bug and and one more parameter than needed.

**Comment by ayufan** [comment]
@ariznaf This is fixed.
